using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class RealtimeButtonModel
{
    [RealtimeProperty(1, true, true)]
    private bool _buttonPressed;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class RealtimeButtonModel : RealtimeModel {
    public bool buttonPressed {
        get {
            return _buttonPressedProperty.value;
        }
        set {
            if (_buttonPressedProperty.value == value) return;
            _buttonPressedProperty.value = value;
            InvalidateReliableLength();
            FireButtonPressedDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(RealtimeButtonModel model, T value);
    public event PropertyChangedHandler<bool> buttonPressedDidChange;
    
    public enum PropertyID : uint {
        ButtonPressed = 1,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _buttonPressedProperty;
    
    #endregion
    
    public RealtimeButtonModel() : base(null) {
        _buttonPressedProperty = new ReliableProperty<bool>(1, _buttonPressed);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _buttonPressedProperty.UnsubscribeCallback();
    }
    
    private void FireButtonPressedDidChange(bool value) {
        try {
            buttonPressedDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _buttonPressedProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _buttonPressedProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.ButtonPressed: {
                    changed = _buttonPressedProperty.Read(stream, context);
                    if (changed) FireButtonPressedDidChange(buttonPressed);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _buttonPressed = buttonPressed;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
