using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class RealtimeCheckoutModel 
{
    [RealtimeProperty(1, true, true)]
    private int _selectedIndex;
    [RealtimeProperty(2, true, true)]
    private bool _buttonPressed;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class RealtimeCheckoutModel : RealtimeModel {
    public int selectedIndex {
        get {
            return _selectedIndexProperty.value;
        }
        set {
            if (_selectedIndexProperty.value == value) return;
            _selectedIndexProperty.value = value;
            InvalidateReliableLength();
            FireSelectedIndexDidChange(value);
        }
    }
    
    public bool buttonPressed {
        get {
            return _buttonPressedProperty.value;
        }
        set {
            if (_buttonPressedProperty.value == value) return;
            _buttonPressedProperty.value = value;
            InvalidateReliableLength();
            FireButtonPressedDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(RealtimeCheckoutModel model, T value);
    public event PropertyChangedHandler<int> selectedIndexDidChange;
    public event PropertyChangedHandler<bool> buttonPressedDidChange;
    
    public enum PropertyID : uint {
        SelectedIndex = 1,
        ButtonPressed = 2,
    }
    
    #region Properties
    
    private ReliableProperty<int> _selectedIndexProperty;
    
    private ReliableProperty<bool> _buttonPressedProperty;
    
    #endregion
    
    public RealtimeCheckoutModel() : base(null) {
        _selectedIndexProperty = new ReliableProperty<int>(1, _selectedIndex);
        _buttonPressedProperty = new ReliableProperty<bool>(2, _buttonPressed);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _selectedIndexProperty.UnsubscribeCallback();
        _buttonPressedProperty.UnsubscribeCallback();
    }
    
    private void FireSelectedIndexDidChange(int value) {
        try {
            selectedIndexDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireButtonPressedDidChange(bool value) {
        try {
            buttonPressedDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _selectedIndexProperty.WriteLength(context);
        length += _buttonPressedProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _selectedIndexProperty.Write(stream, context);
        writes |= _buttonPressedProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.SelectedIndex: {
                    changed = _selectedIndexProperty.Read(stream, context);
                    if (changed) FireSelectedIndexDidChange(selectedIndex);
                    break;
                }
                case (uint) PropertyID.ButtonPressed: {
                    changed = _buttonPressedProperty.Read(stream, context);
                    if (changed) FireButtonPressedDidChange(buttonPressed);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _selectedIndex = selectedIndex;
        _buttonPressed = buttonPressed;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
