using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class RealtimeDoorModel {
    [RealtimeProperty(1, true, true)]
    private bool _open;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class RealtimeDoorModel : RealtimeModel {
    public bool open {
        get {
            return _openProperty.value;
        }
        set {
            if (_openProperty.value == value) return;
            _openProperty.value = value;
            InvalidateReliableLength();
            FireOpenDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(RealtimeDoorModel model, T value);
    public event PropertyChangedHandler<bool> openDidChange;
    
    public enum PropertyID : uint {
        Open = 1,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _openProperty;
    
    #endregion
    
    public RealtimeDoorModel() : base(null) {
        _openProperty = new ReliableProperty<bool>(1, _open);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _openProperty.UnsubscribeCallback();
    }
    
    private void FireOpenDidChange(bool value) {
        try {
            openDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _openProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _openProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Open: {
                    changed = _openProperty.Read(stream, context);
                    if (changed) FireOpenDidChange(open);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _open = open;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
