using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class RealtimeFacialModel
{
    [RealtimeProperty(1, true, true)]
    private RealtimeDictionary<RealtimeGenericFloatValueModel> _entries;

    [RealtimeProperty(2, true, true)]
    private RealtimeDictionary<RealtimeGenericFloatValueModel> _eyeEntries;

    [RealtimeProperty(3, true, true)]
    private Vector3 _eyeGazeDirection;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class RealtimeFacialModel : RealtimeModel {
    public UnityEngine.Vector3 eyeGazeDirection {
        get {
            return _eyeGazeDirectionProperty.value;
        }
        set {
            if (_eyeGazeDirectionProperty.value == value) return;
            _eyeGazeDirectionProperty.value = value;
            InvalidateReliableLength();
            FireEyeGazeDirectionDidChange(value);
        }
    }
    
    public Normal.Realtime.Serialization.RealtimeDictionary<RealtimeGenericFloatValueModel> entries {
        get => _entries;
    }
    
    public Normal.Realtime.Serialization.RealtimeDictionary<RealtimeGenericFloatValueModel> eyeEntries {
        get => _eyeEntries;
    }
    
    public delegate void PropertyChangedHandler<in T>(RealtimeFacialModel model, T value);
    public event PropertyChangedHandler<UnityEngine.Vector3> eyeGazeDirectionDidChange;
    
    public enum PropertyID : uint {
        Entries = 1,
        EyeEntries = 2,
        EyeGazeDirection = 3,
    }
    
    #region Properties
    
    private ModelProperty<Normal.Realtime.Serialization.RealtimeDictionary<RealtimeGenericFloatValueModel>> _entriesProperty;
    
    private ModelProperty<Normal.Realtime.Serialization.RealtimeDictionary<RealtimeGenericFloatValueModel>> _eyeEntriesProperty;
    
    private ReliableProperty<UnityEngine.Vector3> _eyeGazeDirectionProperty;
    
    #endregion
    
    public RealtimeFacialModel() : base(null) {
        RealtimeModel[] childModels = new RealtimeModel[2];
        
        _entries = new Normal.Realtime.Serialization.RealtimeDictionary<RealtimeGenericFloatValueModel>();
        childModels[0] = _entries;
        
        _eyeEntries = new Normal.Realtime.Serialization.RealtimeDictionary<RealtimeGenericFloatValueModel>();
        childModels[1] = _eyeEntries;
        
        SetChildren(childModels);
        
        _entriesProperty = new ModelProperty<Normal.Realtime.Serialization.RealtimeDictionary<RealtimeGenericFloatValueModel>>(1, _entries);
        _eyeEntriesProperty = new ModelProperty<Normal.Realtime.Serialization.RealtimeDictionary<RealtimeGenericFloatValueModel>>(2, _eyeEntries);
        _eyeGazeDirectionProperty = new ReliableProperty<UnityEngine.Vector3>(3, _eyeGazeDirection);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _eyeGazeDirectionProperty.UnsubscribeCallback();
    }
    
    private void FireEyeGazeDirectionDidChange(UnityEngine.Vector3 value) {
        try {
            eyeGazeDirectionDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _entriesProperty.WriteLength(context);
        length += _eyeEntriesProperty.WriteLength(context);
        length += _eyeGazeDirectionProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _entriesProperty.Write(stream, context);
        writes |= _eyeEntriesProperty.Write(stream, context);
        writes |= _eyeGazeDirectionProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Entries: {
                    changed = _entriesProperty.Read(stream, context);
                    break;
                }
                case (uint) PropertyID.EyeEntries: {
                    changed = _eyeEntriesProperty.Read(stream, context);
                    break;
                }
                case (uint) PropertyID.EyeGazeDirection: {
                    changed = _eyeGazeDirectionProperty.Read(stream, context);
                    if (changed) FireEyeGazeDirectionDidChange(eyeGazeDirection);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _entries = entries;
        _eyeEntries = eyeEntries;
        _eyeGazeDirection = eyeGazeDirection;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
