using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class RealtimeVisemeModel
{
    [RealtimeProperty(1, true, true)]
    private RealtimeDictionary<RealtimeGenericFloatValueModel> _entries;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class RealtimeVisemeModel : RealtimeModel {
    public Normal.Realtime.Serialization.RealtimeDictionary<RealtimeGenericFloatValueModel> entries {
        get => _entries;
    }
    
    public enum PropertyID : uint {
        Entries = 1,
    }
    
    #region Properties
    
    private ModelProperty<Normal.Realtime.Serialization.RealtimeDictionary<RealtimeGenericFloatValueModel>> _entriesProperty;
    
    #endregion
    
    public RealtimeVisemeModel() : base(null) {
        RealtimeModel[] childModels = new RealtimeModel[1];
        
        _entries = new Normal.Realtime.Serialization.RealtimeDictionary<RealtimeGenericFloatValueModel>();
        childModels[0] = _entries;
        
        SetChildren(childModels);
        
        _entriesProperty = new ModelProperty<Normal.Realtime.Serialization.RealtimeDictionary<RealtimeGenericFloatValueModel>>(1, _entries);
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _entriesProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _entriesProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Entries: {
                    changed = _entriesProperty.Read(stream, context);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _entries = entries;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
